* Toma de decision usando la tecnología disponible

# Numpy

In [2]:
#numpy
#Crear matrices
distancia_pulgadas = [71.45, 47.43, 91.24, 32.09, 100.23, 98.55]

import numpy as np

#Crear una matriz usando numpy / usando la funcion array()
np_distancia_pulgadas = np.array(distancia_pulgadas)

#Imprimir
print("pulgadas: ",np_distancia_pulgadas)

#Convertir las distancias a metros utilizando operadores algebraicos
np_distancia_metros = np_distancia_pulgadas * 0.0254

#imprimir
print("metros: ", np_distancia_metros)

pulgadas:  [ 71.45  47.43  91.24  32.09 100.23  98.55]
metros:  [1.81483  1.204722 2.317496 0.815086 2.545842 2.50317 ]


In [3]:
#Hacer una matriz de 0 / usando la funcion Zeros()
matriz_de_ceros = np.zeros(4)
print(matriz_de_ceros)

[0. 0. 0. 0.]


In [4]:
#Hacer una matriz de 1 / usando la funcion Ones()
matriz_de_unos = np.ones(4)
print(matriz_de_unos)

[1. 1. 1. 1.]


In [5]:
#Generar array de 10 elementos consecutivos de 2 en 2 desde 2-20
matirz = np.arange(2,20+1,2)
print(matirz)

[ 2  4  6  8 10 12 14 16 18 20]


In [8]:
#Una matriz creada a partir de una tupla
lista1=[1,2,3]
lista2=[7,8,9]
lista3=[6,5,4]
tupla = (lista1, lista2, lista3)
matriz_ = np.array(tupla)
print(matriz_)

[[1 2 3]
 [7 8 9]
 [6 5 4]]


In [10]:
#tipo de arreglo
matriz_.shape

(3, 3)

In [11]:
#tipo de datos
matriz_.dtype

dtype('int64')

In [12]:
#Operacion
operacion = matriz_*2
print(operacion)

[[ 2  4  6]
 [14 16 18]
 [12 10  8]]


In [15]:
#Restar el promedio
print("Matriz original \n",matriz_)
print("Promedio ", matriz_.mean())
operación = matriz_ - matriz_.mean()
print(operación)

Matriz original 
 [[1 2 3]
 [7 8 9]
 [6 5 4]]
Promedio  5.0
[[-4. -3. -2.]
 [ 2.  3.  4.]
 [ 1.  0. -1.]]


In [16]:
#Cambiar datos dentro de un  array
print(matriz_)
copia_matriz = matriz_.copy()


copia_matriz[copia_matriz<=5]=0
print(copia_matriz)

[[1 2 3]
 [7 8 9]
 [6 5 4]]
[[0 0 0]
 [7 8 9]
 [6 0 0]]


In [17]:
#Cambiar datos dentro de un  array
print(matriz_)
copia_matriz = matriz_.copy()

#hacer la primera fila ceros
copia_matriz[0]=0
print(copia_matriz)

[[1 2 3]
 [7 8 9]
 [6 5 4]]
[[0 0 0]
 [7 8 9]
 [6 5 4]]


In [18]:
#Cambiar datos dentro de un  array
print(matriz_)
copia_matriz = matriz_.copy()

#hacer la ultima fila ceros
copia_matriz[2]=0
print(copia_matriz)

[[1 2 3]
 [7 8 9]
 [6 5 4]]
[[1 2 3]
 [7 8 9]
 [0 0 0]]


In [19]:
#Cambiar datos dentro de un  array
print(matriz_)
copia_matriz = matriz_.copy()

#hacer la primera columna ceros
copia_matriz[:,[0]]=0
print(copia_matriz)

[[1 2 3]
 [7 8 9]
 [6 5 4]]
[[0 2 3]
 [0 8 9]
 [0 5 4]]


In [20]:
#Seleccionar datos dentro de un array
print(matriz_)
copia_matriz = matriz_.copy()

#Escoger una columna
print("La columna seleccionada es \n", copia_matriz[:,[1]])

[[1 2 3]
 [7 8 9]
 [6 5 4]]
La columna seleccionada es 
 [[2]
 [8]
 [5]]


In [22]:
#Seleccionar datos dentro de un array
print(matriz_)
copia_matriz = matriz_.copy()

#Escoger un dato
print("El dato seleccionado es \n", copia_matriz[[1],[1]])

[[1 2 3]
 [7 8 9]
 [6 5 4]]
El dato seleccionado es 
 [8]


In [23]:
#Generar 3 grupos de matrices de 2X5
matriz_generada = np.arange(30).reshape(3,2,5)
print(matriz_generada)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [24]:
matriz_generada = np.arange(30).reshape(6,5)
print(matriz_generada)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [25]:
matriz_generada = np.arange(1,1+(3*4)).reshape(3,4)
print(matriz_generada)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
#Vista transversal
matriz_generada = np.arange(1,1+(3*4)).reshape(3,4)
print(matriz_generada.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [27]:
#Crear array de forma aleatoria / un dado
matriz_aleatoria =np.random.randint(1,6)
print(matriz_aleatoria)

5


In [28]:
#Sumar array
matriz1 = np.arange(1,1+4)
print(matriz1)
matriz2 = np.arange(5,5+4)
print(matriz2)
suma = matriz1 +matriz2
print(suma)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]


In [29]:
#Valor maximo de los array
mat1=[5,2,3,7]
mat2=[4,8,6,1]
valor_maximo = np.maximum(mat1,mat2)#Selecciona maximo por columna
print(valor_maximo) #Imprima la matriz con los valores maximos
print(np.max(valor_maximo)) # Imprime el valor maximo

[5 8 6 7]
8


In [1]:
#Resolucion de sistemas de ecuaciones
"""
Supongamos que tenemos el siguiente sistema de ecuaciones y necesitamos resolverlo

x2+x3=5
x1=1 
x3=3
"""

#importar numpy como np
import numpy as np

#definir una matriz A
A = np.array([[0,1,1],[1,0,0],[0,0,1]])

#definir matriz B
B = np.array([[5],[1],[3]])

#Calcular invA
invA = np.linalg.inv(A)

#Imprimir matriz inversa de A
print("Matriz inversa de A es \n", invA) 

#Calcular x
x = invA.dot(B)

#Imprimir la matriz inversar de A
print("x es:\n",x) 

print("No subestimemos el poder de numpy")

Matriz inversa de A es 
 [[ 0.  1.  0.]
 [ 1.  0. -1.]
 [ 0.  0.  1.]]
x es:
 [[1.]
 [2.]
 [3.]]
No subestimemos el poder de numpy


# Ejercicios
* Usar la funcion de interpola; (dentro de 2 lisas ubica los valores e interpola  introduciendo un x1) 

In [2]:
# Datos a y b
a=[11, 22, 33, 99, 55,4]
b=[9, 8, 6, 5, 2, 1]

In [9]:
import numpy as np

x=10
res =  np.interp(x,a,b)

print(res)

1.0


# Pandas